optimize luv_thread_dumped
luvit/luv pull request #596
Opened 2022-05-02 12:39 UTC by zhaozg

2022-05-02 22:09 UTC, squeek502 requested changes

2022-05-02 22:09 UTC, squeek502 commented on src/thread.c
>  // is still on the top of the stack
This comment (including the 'Copied from' line above here) should be removed.

2022-05-02 22:09 UTC, squeek502 commented on src/thread.c
> +    luaL_buffinit(L, &B);
```suggestion
    // In Lua >= 5.4.3, luaL_buffinit pushes a value onto the stack, so it needs to be called
    // here to ensure that the function is at the top of the stack during the lua_dump call
    luaL_buffinit(L, &B);
```

2022-05-03 01:54 UTC, zhaozg commented on src/thread.c
> +    luaL_buffinit(L, &B);
That's clear

2022-05-03 02:13 UTC, squeek502 approved these changes

2022-05-03 02:47 UTC, merged